name: "Check Python file formatting"
on:
  pull_request_target:
    # run on .py and .lit.cfg files
    paths:
      - '**.py'
      - '**.lit.cfg'

jobs:
  python_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.{py,lit.cfg}'

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Python Formatting
        uses: akaihola/darker@1.7.2
        with:
          options: "--check --diff --color ${{ steps.changed-files.outputs.all_changed_files }}"
          version: "~=1.7.2"
          src: ''
