name: Release Task

permissions:
  contents: read

on:
  workflow_dispatch
#  push:

#    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
#      - 'llvmorg-*'

jobs:
  release-tasks:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.validate-tag.outputs.release-version }}
    steps:
      - name: Validate Tag
        id: validate-tag
        run: |
          echo "release-version=17.0.2" >> "$GITHUB_OUTPUT"

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Automation Script
        run: |
          curl -O -L https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/github-automation.py
          curl -O -L https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/requirements.txt
          chmod a+x github-automation.py
          pip install -r requirements.txt

  release-docs:
    needs: release-tasks
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              ninja-build

      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install sphinx myst-parser sphinx-automodapi furo

      - name: Build Documentation
        run: |
          ./llvm/utils/release/build-docs.sh -no-doxygen

      - name: Create Release Notes Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: docs-build/html-export/

  release-lit:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y python3-setuptools

      - name: Test lit
        run: |
          cd llvm/utils/lit
          python3 lit.py tests

      - name: Package lit
        run: |
          cd llvm/utils/lit
          # Remove 'dev' suffix from lit version.
          sed -i "s/ + 'dev'//g" lit/__init__.py
          python3 setup.py sdist

      - name: Upload lit to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LLVM_LIT_TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Upload lit to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LLVM_LIT_PYPI_API_TOKEN }}
