name: Release Task

permissions:
  contents: read

on:
  workflow_dispatch
#  push:

#    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
#      - 'llvmorg-*'

jobs:
  release-tasks:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.validate-tag.outputs.release-version }}
    steps:
      - name: Validate Tag
        id: validate-tag
        run: |
          echo "release-version=17.0.2" >> "$GITHUB_OUTPUT"

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Automation Script
        run: |
          curl -O -L https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/github-automation.py
          curl -O -L https://raw.githubusercontent.com/"$GITHUB_REPOSITORY"/main/llvm/utils/git/requirements.txt
          chmod a+x github-automation.py
          pip install -r requirements.txt

  release-docs:
    needs: release-tasks
    runs-on: ubuntu-latest
    steps:
      - name: Setup clang toolchain
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-16.0.6
          cmake: true
          ninja: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 500M
          key: sccache-${{ matrix.os }}
          variant: sccache

      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install sphinx recommonmark sphinx-automodapi furo sphinx-markdown-tables

      - name: Build Documentation
        env:
          LDFLAGS: -fuse-ld=lld
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
        run: |
          ./llvm/utils/release/build-docs.sh -no-doxygen

      - name: Create Release Notes Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: docs-build/html-export/

  release-doxygen:
    needs: release-tasks
    runs-on: ubuntu-latest
    steps:
      - name: Setup clang toolchain
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-16.0.6
          cmake: true
          ninja: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 500M
          key: sccache-${{ matrix.os }}
          variant: sccache

      - name: Install dependencies
        run: sudo apt-get install -y doxygen graphviz texlive-font-utils

      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install sphinx recommonmark sphinx-automodapi furo sphinx-markdown-tables

      - name: Build Documentation (Doxygen)
        env:
          LDFLAGS: -fuse-ld=lld
          CMAKE_C_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
        run: |
          ./llvm/utils/release/build-docs.sh
#          ./llvm/utils/release/github-upload-release.py --token ${{ github.token }} --release ${{ steps.validate-tag.outputs.release-version }} upload --files ./*doxygen*.tar.xz

  release-lit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup clang toolchain
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-16.0.6
          cmake: true
          ninja: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 500M
          key: sccache-${{ matrix.os }}
          variant: sccache

      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install setuptools

      - name: Build and Test
        uses: llvm/actions/build-test-llvm-project@main
        with:
          cmake_args: '-GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache'
          build_target: 'FileCheck'

      - name: Test lit
        run: |
          cd llvm/utils/lit
          python3 lit.py tests

      - name: Package lit
        run: |
          cd llvm/utils/lit
          # Remove 'dev' suffix from lit version.
          sed -i "s/ + 'dev'//g" lit/__init__.py
          python3 setup.py sdist

      - name: Upload lit to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LLVM_LIT_TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Upload lit to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.LLVM_LIT_PYPI_API_TOKEN }}
